name: reddit_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  fpdart: ^0.5.0
  file_picker: ^5.2.7
  google_sign_in: ^6.0.2
  routemaster: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

